app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', ['as' => 'auth.login', 'uses' => 'AuthController@getLogin']);
    Route::get('register', ['as' => 'auth.register', 'uses' => 'AuthController@postRegister']);
    Route::get('logout', ['as' => 'auth.logout', 'uses' => 'AuthController@getLogout']);

    Route::post('login', ['as' => 'auth.login', 'uses' => 'AuthController@postLogin']);
    Route::post('register', ['as' => 'auth.register', 'uses' => 'AuthController@getRegister']);

});

Route::get('/', ['as' => 'dash.budget.index', 'uses' => 'BudgetController@index', 'middleware' => 'auth']);

Route::group(['middleware' => ['auth'], 'prefix' => 'dash'], function () {
    Route::get('user/json', ['as' => 'dash.user.json', 'uses' => 'UserController@json']);
    Route::resource('user', 'UserController');
    Route::resource('ministry', 'MinistryController');

    Route::get('report_income', function () {
        return view('budget.report_income');
    });

    Route::get('report_expense', function () {
        return view('budget.report_expense');
    });

    // list
    Route::get('budget', ['as' => 'dash.budget.index', 'uses' => 'BudgetController@index']);
    Route::get('budget/json', ['as' => 'dash.budget.json', 'uses' => 'BudgetController@json']);

    // approve
    Route::get('budget/approve/{type}/{id}', ['as' => 'dash.budget.get_approve', 'uses' => 'BudgetController@getApprove']);
    Route::patch('budget/approve/{budget}', ['as' => 'dash.budget.patch_approved', 'uses' => 'BudgetController@patchApprove']);

    // create
    Route::get('budget/create/income', ['as' => 'dash.budget.create_income', 'uses' => 'BudgetController@create_income']);
    Route::get('budget/create/expense', ['as' => 'dash.budget.create_expense', 'uses' => 'BudgetController@create_expense']);

    // store
    Route::post('budget/create/income', ['as' => 'dash.budget.store_income', 'uses' => 'BudgetController@store_income']);
    Route::post('budget/create/expense', ['as' => 'dash.budget.store_expense', 'uses' => 'BudgetController@store_expense']);

    // edit
    Route::get('budget/income/{budget}/edit', ['as' => 'dash.budget.edit_income', 'uses' => 'BudgetController@edit_income']);
    Route::get('budget/expense/{budget}/edit', ['as' => 'dash.budget.edit_expense', 'uses' => 'BudgetController@edit_expense']);

    // update
    Route::patch('budget/income/{budget}', ['as' => 'dash.budget.update_income', 'uses' => 'BudgetController@update_income']);
    Route::patch('budget/expense/{budget}', ['as' => 'dash.budget.update_expense', 'uses' => 'BudgetController@update_expense']);
});

resources/views/auth.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url('favicon.ico') }}">
    <title>@yield('title')</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{{url('fonts/khmer/khmer-webfonts.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url('css/bootstrap.min.css')}}">
    <!-- Custom styles for this template -->
    <link href="{{url('css/navbar-fixed-top.css')}}" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{url('js/ie-emulation-modes-warning.js')}}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
        body {
            background-color: #edf8f6;
        }
        * {
            border-radius: 1px !important;
        }
        .btn-block {
            margin-top:15px;
            margin-bottom: 15px;
        }

        h3 {
            text-align: center;
        }

        .auth-container {
            margin-top: 70px;
        }
        /*.auth-content {
            -webkit-box-shadow: 10px 10px 18px 0px rgba(39,59,79,1);
            -moz-box-shadow: 10px 10px 18px 0px rgba(39,59,79,1);
            box-shadow: 10px 10px 18px 0px rgba(39,59,79,1);
        }*/
        h1, h2, h3, h4 { font-family: 'KhmerOSmuol' }
        p, input { font-family: 'KhmerOSbattambang' }
    </style>
</head>

<body>

    <div class="container" style="width: 450px; margin-top: 50px;">


        @yield('content')

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{{url('js/jquery-1.11.3.min.js')}}"></script>
    <script type="text/javascript" src="{{url('js/bootstrap.min.js')}}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{url('js/ie10-viewport-bug-workaround.js')}}"></script>
    @stack('scripts')
</body>

</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url('favicon.ico') }}">
    <title>@yield('title')</title>

    <!-- Bootstrap core CSS -->
    {!! HTML::style('fonts/khmer/khmer-webfonts.css') !!}
    {!! HTML::style('css/khmer-font.css') !!}
    {!! HTML::style('css/bootstrap.min.css', ["media" => "screen"]) !!}

    <!-- Custom styles for this template -->
    {!! HTML::style('css/bootstrap-custome-theme.css', ["media" => "screen"]) !!}

    {{-- Custom style for Virak --}}
    {!! HTML::style('css/virak/style.css', ["media" => "screen"]) !!}

    {{-- Print style by Ravuth --}}
    {!! HTML::style('css/print.css', ["media" => "print"]) !!}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{url('js/ie-emulation-modes-warning.js')}}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body data-link="{!! url() !!}">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top no-print">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{{url()}}">
                    <img src="{{url('img/logo.png')}}" height="50px" width="auto">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                        @if (Auth::user()->role == 'admin')
                        <li class="{{ Request::is('dash.user') ? 'active' : '' }}">
                            {!! link_to_route('dash.user.index', 'គ្រប់គ្រងគណនីរបស់អ្នកប្រើប្រាស់') !!}
                        </li>
                        <li class="{{ Request::is('dash.ministry') ? 'active' : '' }}">
                            {!! link_to_route('dash.ministry.index', 'គ្រប់គ្រងក្រសួង') !!}
                        </li>
                    @endif
                    {{-- <li class="{{ Request::is('dash.report') ? 'active' : '' }}">
                        {!! link_to_route('dash.report', 'របាយការណ៏') !!}
                    </li> --}}
                    {{-- <li class="{{ Request::is('dash.report') ? 'active' : '' }}">
                        {!! Html::link('#report', 'បង្ហាញរបាយការណ៏', ['id' => 'btnShowReport']) !!}
                    </li>
                    <li class="{{ Request::is('dash.report') ? 'active' : '' }}">
                        <a href="javascript:" id="btnShowReport">បង្ហាញរបាយការណ៏</a>
                    </li>
                    <li class="{{ Request::is('dash.report') ? 'active' : '' }}">
                        <a href="javascript:" id="btnHideReport">បង្ហាញរបាយការណ៏</a>
                    </li> --}}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {!! link_to_route('dash.user.edit', ucfirst(Auth::user()->username), Auth::user()->id) !!}
                    </li>
                    <li>{!! link_to_route('auth.logout', 'ចាកចេញ') !!}</li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container" style="padding: 10px 15px 0 !important">
        @yield('content')
    </div>
    <br/>
    <br/>
    <br/>
    <footer class="footer no-print">
        <div class="container">
            <center class="text-muted">
                <p>អាគារលេខ ១៩ រុក្ខវិថីព្រះមហាក្សត្រីយានីកុសមៈ (ផ្លូវលេខ ១០៦) សង្កាត់វត្តភ្នំ ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ ព្រះរាជាណាចក្រកម្ពុជាអគ្គនាយកដ្ឋានរតនាគារជាតិ</p>
                <p class="en">General Department of National Treasury</p>
            </center>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{{url('js/jquery-1.11.3.min.js')}}"></script>
    <script type="text/javascript" src="{{url('js/bootstrap.min.js')}}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{url('js/ie10-viewport-bug-workaround.js')}}"></script>
    {!! HTML::style('css/bootstrap-datetimepicker.min.css') !!} {{-- {!! HTML::script('js/jquery-1.11.3.min.js') !!} --}} {!! HTML::script('js/moment.min.js') !!} {{-- {!! HTML::script('js/bootstrap.min.js') !!} --}} {!! HTML::script('js/bootstrap-datetimepicker.min.js') !!}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
    {!! HTML::style('css/dataTables.bootstrap.min.css') !!}
    {!! HTML::script('js/jquery.dataTables.min.js') !!}
    {!! HTML::script('js/dataTables.bootstrap.min.js') !!}
    {!! HTML::script('js/dash.config.js') !!}
    @stack('scripts')
    <!-- Custom script Virak -->
    <script src="{{url('js/customs/ministry.js')}}"></script>
</body>

</html>