app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', ['as' => 'auth.login', 'uses' => 'AuthController@getLogin']);
    Route::get('register', ['as' => 'auth.register', 'uses' => 'AuthController@postRegister']);
    Route::get('logout', ['as' => 'auth.logout', 'uses' => 'AuthController@getLogout']);

    Route::post('login', ['as' => 'auth.login', 'uses' => 'AuthController@postLogin']);
    Route::post('register', ['as' => 'auth.register', 'uses' => 'AuthController@getRegister']);

});

Route::get('/', ['as' => 'dash.budget.index', 'uses' => 'BudgetController@index', 'middleware' => 'auth']);

Route::group(['middleware' => ['auth'], 'prefix' => 'dash'], function () {
    Route::get('user/json', ['as' => 'dash.user.json', 'uses' => 'UserController@json']);
    Route::resource('user', 'UserController');
    Route::resource('ministry', 'MinistryController');

    Route::get('report_income', function () {
        return view('budget.report_income');
    });

    Route::get('report_expense', function () {
        return view('budget.report_expense');
    });

    // list
    Route::get('budget', ['as' => 'dash.budget.index', 'uses' => 'BudgetController@index']);
    Route::get('budget/json', ['as' => 'dash.budget.json', 'uses' => 'BudgetController@json']);

    // approve
    Route::get('budget/approve/{type}/{id}', ['as' => 'dash.budget.get_approve', 'uses' => 'BudgetController@getApprove']);
    Route::patch('budget/approve/{budget}', ['as' => 'dash.budget.patch_approved', 'uses' => 'BudgetController@patchApprove']);

    // create
    Route::get('budget/create/income', ['as' => 'dash.budget.create_income', 'uses' => 'BudgetController@create_income']);
    Route::get('budget/create/expense', ['as' => 'dash.budget.create_expense', 'uses' => 'BudgetController@create_expense']);

    // store
    Route::post('budget/create/income', ['as' => 'dash.budget.store_income', 'uses' => 'BudgetController@store_income']);
    Route::post('budget/create/expense', ['as' => 'dash.budget.store_expense', 'uses' => 'BudgetController@store_expense']);

    // edit
    Route::get('budget/income/{budget}/edit', ['as' => 'dash.budget.edit_income', 'uses' => 'BudgetController@edit_income']);
    Route::get('budget/expense/{budget}/edit', ['as' => 'dash.budget.edit_expense', 'uses' => 'BudgetController@edit_expense']);

    // update
    Route::patch('budget/income/{budget}', ['as' => 'dash.budget.update_income', 'uses' => 'BudgetController@update_income']);
    Route::patch('budget/expense/{budget}', ['as' => 'dash.budget.update_expense', 'uses' => 'BudgetController@update_expense']);
});

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Access\Authorizable;

class User extends Model implements AuthenticatableContract,
AuthorizableContract,
CanResetPasswordContract {
    use Authenticatable, Authorizable, CanResetPassword;

    protected $table = 'users';
    
    protected $dates = ['date_of_birth'];

    protected $fillable = ['firstname', 'lastname', 'username', 'date_of_birth', 'password', 'email', 'role', 'gender', 'ministry_id', 'status'];

    protected $hidden = ['remember_token'];

    public function adminIncomes() {
        return $this->hasMany('App\AdminIncome', 'user_id', 'id');
    }

    public function adminExpense() {
        return $this->hasMany('App\AdminExpense', 'user_id', 'id');
    }

    public function incomes() {
        return $this->hasMany('App\UserIncome', 'user_id', 'id');
    }

    public function expense() {
        return $this->hasMany('App\UserExpense', 'user_id', 'id');
    }

    public function ministries() {
        return $this->hasMany('App\Ministry', 'created_by');
    }

    public function ministry() {
        return $this->hasOne('App\Ministry', 'id', 'ministry_id');
    }

    public function getDateOfBirthAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d-m-Y');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Ministry;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;

class UserController extends Controller {
    public function __construct() {
        parent::__construct();
        if ($this->user->role == 'user') {
            $this->middleware('admin', ['except' => ['edit', 'update']]);
        }
    }

    public function index() {
        return view('user.index');
    }

    public function json() {
        if ($this->user->username == 'superadmin') {
            return User::all();
        } else {
            return User::where('role', 'user')->get();
        }
    }

    public function create() {
        $data['ministry'] = null;
        $data['ministries'] = Ministry::lists('name', 'id');
        return view('user.create', $data);
    }

    public function store(UserRequest $request) {
        $user = $request->all();
        $user['date_of_birth'] = Carbon::parse($request->input('date_of_birth'));
        $user['password'] = bcrypt($request->password);
        $user['status'] = "on";
        $message['user'] = User::create($user);
        $message['password'] = $request->password;
        $message['title'] = 'CMS: Create New User';

        $this->send($message);


        return redirect('dash/user');
    }

    public function show(User $user) {
        if ($this->user->role == 'admin') {
            if ($user->role == $this->user->role && $this->user->id != $user->id) {
                return redirect()->route('auth.logout');
            }
        } else if ($this->user->id != $user->id) {
            return redirect()->route('auth.logout');
        }

        $data['user'] = $user;
        $data['ministry'] = null;
        $data['ministries'] = Ministry::lists('name', 'id');

        return view('user.show', $data);
    }

    public function edit(User $user) {
        if ($this->user->role == 'admin') {
            if ($user->role == $this->user->role && $this->user->id != $user->id) {
                return redirect()->route('auth.logout');
            }
        } else if ($this->user->id != $user->id) {
            return redirect()->route('auth.logout');
        }
        $data['user'] = $user;
        $data['ministry'] = $user->ministry->id;
        $data['ministries'] = Ministry::lists('name', 'id');
        return view('user.edit', $data);
    }

    public function update(UserRequest $request, User $user) {
        $data = $request->except(['password', 'password_confirmation']);
        $data['date_of_birth'] = Carbon::parse($request->input('date_of_birth'));
        if (!empty($request->password) || !empty($request->password_confirmation)) {
            $data['password'] = bcrypt($request->password);
        }
        $user->update($data);

        $message['user'] = $user;
        $message['password'] = $request->password;
        $message['title'] = 'CMS: Update Exists User';

        $this->send($message);

        if ($this->user->role == 'user') {
            return redirect('/');
        }

        return redirect('dash/user');
    }

    public function destroy(User $user) {
        $user->delete();
        if (\Request::ajax()) {
            return ['result' => true];
        }
        return redirect('dash/user');
    }
}

resources/views/user/create.blade.php
@extends('master')


@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">បង្កើតគណនី</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8">
                    @include('errors.validate')
                    {!! Form::open(['route' => 'dash.user.store']) !!}
                        @include('user.form',  ['submittype' => 'Add'])
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

    <hr/><br/>
@stop

resources/views/user/edit.blade.php
@extends('master')


@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">កែសម្រួលគណនី របស់អ្នកប្រើប្រាស់ {!! ucfirst($user->username) !!}</h1>
        </div>
    </div>
   
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8">
                    @include('errors.validate')
                    {!! Form::model($user, ['method' => 'PATCH', 'action' => ['UserController@update', $user->id]])!!}
                        @include('user.form', ['submittype' => 'Update'])
                    {!! Form::close() !!}
                </div>
            </div>
        </div>

    </div>
            <hr/><br/>
@stop

resources/views/user/form.blade.php
@if (Auth::user()->role == "admin")
    <div class="row">

        <div class="form-group col-md-6">
            {!! Form::label('ministry_id','ក្រសួង') !!}
            {!! Form::select('ministry_id', $ministries, $ministry, ['placeholder' => 'សូមជ្រើសរើស ...', 'class' => 'form-control']) !!}
        </div>

        <div class="form-group col-md-6">
            {!! Form::label('role','តួនាទី') !!}
            {!! Form::select('role', ['user' => 'User', 'admin' => 'Admin', 'manager' => 'Manager'], null, ['placeholder' => 'សូមជ្រើសរើស ...', 'class' => 'form-control']) !!}
        </div>
    </div>
@endif

{{-- */$disabled = !empty($user) ? 'disabled' : '';/* --}}

<div class="row">
    <div class="form-group col-md-6">
        {!! Form::label('firstname','ឈ្មោះ') !!}
        {!! Form::text('firstname', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group col-md-6">
        {!! Form::label('lastname','នាមត្រកូល') !!}
        {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="row">
    <div class="form-group col-md-6">
        {!! Form::label('username','ឈ្មោះគណនី') !!}
        {!! Form::text('username', null, ['class' => 'form-control', $disabled]) !!}
    </div>
    <div class="form-group col-md-6">
        {!! Form::label('date_of_birth','ថ្ងៃខែ​ឆ្នាំ​កំណើត') !!}
        {!! Form::text('date_of_birth', null, ['class' => 'form-control', 'id' => 'txtDOB']) !!}
    </div>
</div>
<div class="row">
    <div class="form-group col-md-6">
        {!! Form::label('password','ពាក្យសម្ងាត់') !!}
        {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '*********']) !!}
    </div>
    <div class="form-group col-md-6">
        {!! Form::label('ផ្ទៀងផ្ទាត់ ពាក្យសម្ងាត់','ផ្ទៀងផ្ទាត់ ពាក្យសម្ងាត់') !!}
        {!! Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => '*********']) !!}
    </div>
</div>
<div class="row">
    <div class="form-group col-md-6">
        {!! Form::label('email','អ៊ីម៉ែល') !!}
        {!! Form::email('email', null, ['class' => 'form-control', $disabled]) !!}
    </div>
    <div class="form-group col-md-3">
        {!! Form::label('gender','ភេទ') !!}
        {!! Form::select('gender', ['' => 'សូមជ្រើសរើស ...', 'male' => 'Male', 'female' => 'Female'], null, ['placeholder' => 'សូមជ្រើសរើស ...', 'class' => 'form-control']) !!}
    </div>
    <div class="form-group col-md-3">
        {!! Form::label('status','ឯកសិទ្ធិ') !!}
        {!! Form::select('status', ['1' => 'on', '0' => 'off'], null, ['placeholder' => 'សូមជ្រើសរើស ...', 'class' => 'form-control']) !!}
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-4 pull-right">
        <div class="form-group">
            {!! link_to_route('dash.budget.index', 'ចាកចេញ', null, ['class' => 'btn btn-block btn-default']) !!}
        </div>
    </div>
    <div class="col-md-4 pull-right">
        <div class="form-group">
            {!! Form::submit('រក្សាទុក', ['class' => 'btn btn-block btn-info']) !!}
        </div>
    </div>
</div>
@push('scripts')
<script type="text/javascript">
$(function() {
    $('#txtDOB').datepicker({
        format: "dd-mm-yyyy",
        autoclose: true,
        language: 'kh',
    });

    // var $('.password').attr({
    //     type: 'password',
    //     placeholder: '*********'
    // });

    // var old = $('.password').first().val();
    // $('.password').attr('type', 'password').val(old);
});
</script>
@endpush

resources/views/user/index.blade.php
@extends('master')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">បញ្ជីឈ្មោះអ្នកប្រើ
                {!! link_to_route('dash.user.create', 'បន្ថែមថ្មី', null, ['class' => 'btn btn-default pull-right']) !!}
            </h2>
        </div>
    </div>
    <table class="table table-bordered table-hover myStyle" id="tblUsers">
        <thead>
            <tr>
                <th>ឈ្មោះគណនី</th>
                <th>ឈ្មោះ</th>
                <th>នាមត្រកូល</th>
                <th>អ៊ីម៉ែល</th>
                <th>ភេទ</th>
                <th>ថ្ងៃខែ​ឆ្នាំ​កំណើត</th>
                <th>ធ្វើការកែប្រែ</th>
            </tr>
        </thead>
    </table>
    <hr/><br/>
@stop

@push('scripts')
    <script type="text/javascript">
        var _link = '{{ url() }}/';
        var _code = '{{ csrf_token() }}';
    </script>

    {!! HTML::style('css/datatables.css') !!}
    {!! HTML::script('js/datatables.js') !!}
    {!! HTML::script('js/user.js') !!}
@endpush

resources/views/user/show.blade.php
@extends('master') @section('content')
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">ពត៌មានលមិ្ឣតរបស់៖​​ {{$user->username}}</h2>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="id">ក្រសួង </label>
                        <p class="form-control">{{ $user->ministry->name }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id">តួនាទី </label>
                        <p class="form-control">{{ $user->role }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="id">ឈ្មោះ </label>
                        <p class="form-control">{{ $user->firstname }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="firstname">នាមត្រកូល </label>
                        <p class="form-control">{{ $user->lastname }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="id" class="text-danger">ឈ្មោះគណនី </label>
                        <p class="form-control">{{ $user->username }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id">ថ្ងៃខែ​ឆ្នាំ​កំណើត </label>
                        <p class="form-control">{{ $user->date_of_birth }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="firstname" class="text-danger">អ៊ីម៉ែល </label>
                        <p class="form-control">{{ $user->email }}</p>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="id">ភេទ</label>
                        <p class="form-control">{{ $user->gender }}</p>
                    </div>

                    <div class="form-group col-md-3">
                        {!! Form::label('status','ឯកសិទ្ធិ') !!}
                        {!! Form::select('status', ['1' => 'on', '0' => 'off'], $user->status , ['class' => 'form-control disabled', 'disabled']) !!}
                    </div>
                   
                </div>
                <div class="row">
                    <div class="col-md-4 pull-right">
                        <div class="form-group">
                            {!! link_to_route('dash.user.index', 'ចាកចេញ', null, ['class' => 'btn btn-block btn-default']) !!}
                        </div>
                    </div>
                    <div class="col-md-4 pull-right">
                        <div class="form-group">
                            {!! link_to_route('dash.user.edit', 'ធ្វើការកែសម្រួល', $user->id, ['class' => 'btn btn-block btn-info']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr/>
<br/> @stop